In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('we_fn_use_c_marketing_customer_value_analysis.csv')
data.head()

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

In [3]:
data.dtypes

Customer                          object
State                             object
Customer Lifetime Value          float64
Response                          object
Coverage                          object
Education                         object
Effective To Date                 object
EmploymentStatus                  object
Gender                            object
Income                             int64
Location Code                     object
Marital Status                    object
Monthly Premium Auto               int64
Months Since Last Claim            int64
Months Since Policy Inception      int64
Number of Open Complaints          int64
Number of Policies                 int64
Policy Type                       object
Policy                            object
Renew Offer Type                  object
Sales Channel                     object
Total Claim Amount               float64
Vehicle Class                     object
Vehicle Size                      object
dtype: object

In [9]:
import numpy as np
import pandas as pd

def es_discreta(data):
   
    if np.issubdtype(data.dtype, np.integer):
        return True
    
    elif np.issubdtype(data.dtype, np.bool_):
        return True
  
    elif np.issubdtype(data.dtype, np.str_) or np.issubdtype(data.dtype, np.unicode_):
        return True
    
    else:
        return False

for columna in data.columns:
    columna_data = data[columna]
    es_columna_discreta = es_discreta(columna_data)
    
    if es_columna_discreta:
        print(f" '{columna}'has discret data.")
    else:
        print(f"'{columna}' has continuos data.")

'Customer' has continuos data.
'State' has continuos data.
'Customer Lifetime Value' has continuos data.
'Response' has continuos data.
'Coverage' has continuos data.
'Education' has continuos data.
'Effective To Date' has continuos data.
'EmploymentStatus' has continuos data.
'Gender' has continuos data.
 'Income'has discret data.
'Location Code' has continuos data.
'Marital Status' has continuos data.
 'Monthly Premium Auto'has discret data.
 'Months Since Last Claim'has discret data.
 'Months Since Policy Inception'has discret data.
 'Number of Open Complaints'has discret data.
 'Number of Policies'has discret data.
'Policy Type' has continuos data.
'Policy' has continuos data.
'Renew Offer Type' has continuos data.
'Sales Channel' has continuos data.
'Total Claim Amount' has continuos data.
'Vehicle Class' has continuos data.
'Vehicle Size' has continuos data.